import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Navbar from './navbar'
import Card from './card'
import Footer from './footer'
import { documentToReactComponents } from '@contentful/rich-text-react-renderer';
import Link from 'next/link'
import data from "../public/data.json";
export default function Home() {
  const {fields:{
    body,
    title,
    author,
    published,
    Site,
    posts,
    banner: {
       fields: {
        title: imgTitle,
        file:{url:url}}}}}= data;
  console.log('posts',posts);
  return (
    <>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <div className={styles.img}>
        <a href='https://www.hermanmiller.com/en_in/' target='_blank'><Image src="hm-logo-caption.svg" alt="My Image" width={200} height={40}  /></a>
        <Navbar />
      </div>
      <div>
      <div>
        <h2 className="h3">Overview</h2>
        <div className={styles.grid}>
       {/* <Card> */}
       <Image className="ia"
             src={'https://images.ctfassets.net/2gmj7mnwoa4a/1nRlt0hunAq2130s5LxcSc/41d3621c2d46499f3265391ff73064d0/cc.jpg'} 
             width={378} height={179}/> 
        <Image className="ia1"
             src={'https://images.ctfassets.net/2gmj7mnwoa4a/1nRlt0hunAq2130s5LxcSc/41d3621c2d46499f3265391ff73064d0/cc.jpg'} 
             width={378} height={179}/> 
              <Image className="ia2"
             src={'https://images.ctfassets.net/2gmj7mnwoa4a/1nRlt0hunAq2130s5LxcSc/41d3621c2d46499f3265391ff73064d0/cc.jpg'} 
             width={378} height={179}/> 
        {posts.map(
          ({
            sys: {id},
            fields:{author,banner,body,published,title}}) => {
          
          return <div key={id}>
            <div className={styles.posts}>
            <div className="align" >
              {author}.&nbsp;{published}
              </div>
            <div>{title}</div>
           <div className={styles.des}>
            { documentToReactComponents(body)}
            </div>
            </div>;
            </div>
        })} 
        </div>
        {/* </Card> */}
       {/* <Card />
       <Card /> */}
      
       {/* </div> */}
       {/*  {posts.map(({sys: {id},fields:{description}}) => {
          //console.log("fields",fields);
          return <div key={id}> {documentToReactComponents(description)}</div>;
        })} */}
      </div>
      {/* <div className={styles.grid}>
            <Card>
             <Image className="ia"
             src={'https://images.ctfassets.net/2gmj7mnwoa4a/1nRlt0hunAq2130s5LxcSc/41d3621c2d46499f3265391ff73064d0/cc.jpg'} 
             width={378} height={179}/> 
             <h3 className="author">
              {author}.&nbsp;{published}
            </h3>
              <div><h2 className="title">{title}</h2></div>
              {/* <div><h4 className="title">{data.fields.title}</h4></div> */}
            
            {/* <h3 className="author">
              {author}.&nbsp;{published}
            </h3>
            
            <h2 className="title">
              {title}
            </h2>
            <div className="des">{documentToReactComponents(body)}</div> */}
           {/* <div className="des">{documentToReactComponents(body)}</div>

          </Card>
        <Card>
        
      
        </Card>
        <Card >
          <h2> Blog3</h2>
        </Card>
        <Card>
          <h2> Blog4</h2>
        </Card>
     </div>
      </div>
      <div> */} 
        <Footer />
      </div>
      </main>
    </>
  )
}